name: Flutter CI/CD

on: [push]

jobs:
  build:
    name: Run Tests & Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Determine New Release Version
        id: determine_version
        run: echo "RELEASE_VERSION=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Build the Flutter app
        run: flutter build apk --release --split-per-abi

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: ${{ env.RELEASE_VERSION }}
          token: ${{ secrets.TOKEN }}
