on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
name: "Build and Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}